### ISSUE TITLE
Create screen for profile page

### ISSUE THREAD

**Issue by acomanzo** [ICSI-499-Team-3/frontend#13]
Create a screen for the user's profile. The screen should have buttons to reset email, reset password, connect their account to Garmin, FitBit, Apple Health, Google Fit, Strava, and OuraRing. 

sketches:
[22_profile_page](https://user-images.githubusercontent.com/33241429/139736846-8636e740-63e8-43db-b6e8-2b4a66e71aeb.jpg)

**Comment by haffinnih** [comment]
In progress, see b3933bbf2c9f82b9aed7168423305e8b66297c2c.

Todo:

- [x] Logout (needs bugfixing)
- [x] Reset email
- [x] Reset password
- [ ] External connections

 Connect to:

- [ ] Garmin
- [ ] FitBit
- [ ] Apple Health
- [ ] Google Fit
- [ ] Strava
- [ ] OuraRing
