### ISSUE TITLE
Create sign in screen

### ISSUE THREAD

**Issue by acomanzo** [ICSI-499-Team-3/frontend#16]
Create a screen for the user to sign in to their account. This should be the first screen the user sees when using the app. It should prompt the user for their email and password. There should be a button to log in; when the user clicks this button, it should check the db to see if the user inputted the proper info. At the bottom of the screen there should be a prompt to sign up if the user is a new user. 

sketches: 
[26_sign_in](https://user-images.githubusercontent.com/33241429/139739092-1b1ad9a8-758a-46f9-b7a1-1b79229a5fb6.jpg)

**Comment by haffinnih** [comment]
Mostly integrated in b3933bbf2c9f82b9aed7168423305e8b66297c2c.

Todo:

- [x] Create sign-in screen
- [x] Link to sign up screen
- [x] Link to forgot password screen for #14
- [x] Integrate with backend and return credentials
- [x] Persist user data once logged in (email, name, authToken)
- [ ] Fix bug with causes "incorrect password" toast to appear after a consecutive incorrect, then correct login sequence

**Comment by haffinnih** [comment]
Splitting the bug into its own issue and closing this one
