### ISSUE TITLE
Create sign up screen

### ISSUE THREAD

**Issue by acomanzo** [ICSI-499-Team-3/frontend#17]
Create a screen for the user to create a new account. The screen should prompt the user for an email, a password, and then to confirm their password. When the user clicks the sign up button, it should check if the email exists for another user in the database already. If it does, it should tell the user the email is taken. If not, then it should create a user. Ideally, this screen should also have the user verify their email using the same flow from #14 . After the user signs up, it should log them in and bring them to the main screen. 

sketches:
[27_sign_up](https://user-images.githubusercontent.com/33241429/139739528-edb5fca7-ac8e-43e7-afa9-65e6f6766292.jpg)

**Comment by haffinnih** [comment]
Mostly integrated in b3933bbf2c9f82b9aed7168423305e8b66297c2c.

- [x] User Account creation screen with name, email, password
- [x] Connect to the backend to persist account data
- [x] Alert user email is taken if it's taken
- [x] Add another box to confirm password
- [ ] Integrate with password reset flow #14 (not yet created)
- [ ] Automatically log the user in

**Comment by haffinnih** [comment]
Splitting integration with password reset into a separate issue and closing this one
